modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''${description}'''
logoFile="assets/customhud/icon.png"
displayURL="https://modrinth.com/project/beautiful-day-counter"
issueTrackerURL="https://github.com/sonoFrangu/CustomHUD/issues"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
